/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package messender.ui;

import java.net.BindException;

import messender.server.Session;

/**
 * @author Ashanti
 */
public class SenderPage extends javax.swing.JFrame {
    
    /**
     * Creates new form HomePage
     */
    public SenderPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainFrame = new javax.swing.JPanel();
        upperBar = new javax.swing.JPanel();
        sendMenu = new javax.swing.JButton();
        addFriendMenu = new javax.swing.JButton();
        themeMenu = new javax.swing.JButton();
        homeMenu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        sendingPanel = new javax.swing.JPanel();
        messagePanel = new javax.swing.JPanel();
        sendMessBtn = new javax.swing.JButton();
        messageField = new javax.swing.JTextField();
        leftPanel1 = new javax.swing.JPanel();
        friendList = new javax.swing.JList<>();
        topLeftPanel1 = new javax.swing.JPanel();
        friendListLbl = new javax.swing.JLabel();
        delFriendBtn = new javax.swing.JButton();
        errorSendingLbl = new javax.swing.JLabel();
        addFriendPanel = new javax.swing.JPanel();
        portLbl = new javax.swing.JLabel();
        portField = new javax.swing.JTextField();
        nameLbl = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        hostLbl = new javax.swing.JLabel();
        hostField = new javax.swing.JTextField();
        nicknameLbl = new javax.swing.JLabel();
        nicknameField = new javax.swing.JTextField();
        addFriendBtn = new javax.swing.JButton();
        errorAddFriendLbl = new javax.swing.JLabel();
        leftPanel = new javax.swing.JPanel();
        friendRequestList = new javax.swing.JList<>();
        topLeftPanel = new javax.swing.JPanel();
        friendRequestListLbl = new javax.swing.JLabel();
        acceptFriendBtn = new javax.swing.JButton();
        contentPage = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        mainFrame.setBackground(new java.awt.Color(255, 255, 255));
        mainFrame.setPreferredSize(new java.awt.Dimension(800, 600));
        mainFrame.setLayout(null);

        upperBar.setBackground(new java.awt.Color(255, 132, 149));
        upperBar.setPreferredSize(new java.awt.Dimension(400, 500));
        upperBar.setLayout(new java.awt.GridLayout(1, 0));

        sendMenu.setBackground(new java.awt.Color(255, 132, 149));
        sendMenu.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        sendMenu.setIcon(new javax.swing.ImageIcon("image/icon/sent.png")); // NOI18N
        sendMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(251, 163, 163)));
        sendMenu.setMaximumSize(new java.awt.Dimension(84, 28));
        sendMenu.setMinimumSize(new java.awt.Dimension(84, 28));
        sendMenu.setPreferredSize(new java.awt.Dimension(84, 28));
        sendMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendMenuActionPerformed(evt);
            }
        });
        upperBar.add(sendMenu);

        addFriendMenu.setBackground(new java.awt.Color(255, 132, 149));
        addFriendMenu.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        addFriendMenu.setIcon(new javax.swing.ImageIcon("images/icons/friend.png")); // NOI18N
        addFriendMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(251, 163, 163)));
        addFriendMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFriendMenuActionPerformed(evt);
            }
        });
        upperBar.add(addFriendMenu);

        themeMenu.setBackground(new java.awt.Color(255, 132, 149));
        themeMenu.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        themeMenu.setIcon(new javax.swing.ImageIcon("images/icons/theme.png")); // NOI18N
        themeMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(251, 163, 163)));
        themeMenu.setMaximumSize(new java.awt.Dimension(84, 28));
        themeMenu.setMinimumSize(new java.awt.Dimension(84, 28));
        themeMenu.setPreferredSize(new java.awt.Dimension(84, 28));
        upperBar.add(themeMenu);

        homeMenu.setBackground(new java.awt.Color(255, 132, 149));
        homeMenu.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        homeMenu.setIcon(new javax.swing.ImageIcon("images/icons/home.png")); // NOI18N
        homeMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(251, 163, 163)));
        homeMenu.setMaximumSize(new java.awt.Dimension(84, 28));
        homeMenu.setMinimumSize(new java.awt.Dimension(84, 28));
        homeMenu.setPreferredSize(new java.awt.Dimension(84, 28));
        homeMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeMenuActionPerformed(evt);
            }
        });
        upperBar.add(homeMenu);
        upperBar.add(jLabel1);
        upperBar.add(jLabel2);
        upperBar.add(jLabel3);
        upperBar.add(jLabel4);
        upperBar.add(jLabel5);

        mainFrame.add(upperBar);
        upperBar.setBounds(0, 0, 800, 50);

        SendingPanel sendingP;



        contentPage.setBackground(new java.awt.Color(255, 234, 233));
        contentPage.setPreferredSize(new java.awt.Dimension(800, 600));
        contentPage.setRequestFocusEnabled(false);
        contentPage.setLayout(null);
        try {
            sendingP = new SendingPanel( new Session("test", 0) );
            contentPage.add( sendingP );
            sendingP.setBounds(0, 0, 800, 550);
        } catch (BindException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
        
        mainFrame.add(contentPage);
        contentPage.setBounds(0, 50, 800, 550);

        addFriendPanel.setBackground(new java.awt.Color(255, 234, 233));
        addFriendPanel.setMinimumSize(new java.awt.Dimension(800, 600));
        addFriendPanel.setLayout(null);

        portLbl.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        portLbl.setForeground(new java.awt.Color(204, 105, 119));
        portLbl.setText("Port");
        addFriendPanel.add(portLbl);
        portLbl.setBounds(260, 80, 50, 20);

        portField.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        portField.setSelectedTextColor(new java.awt.Color(193, 187, 234));
        portField.setSelectionColor(new java.awt.Color(193, 187, 234));
        portField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                portFieldActionPerformed(evt);
            }
        });
        addFriendPanel.add(portField);
        portField.setBounds(260, 100, 210, 30);

        nameLbl.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        nameLbl.setForeground(new java.awt.Color(204, 105, 119));
        nameLbl.setText("Name");
        addFriendPanel.add(nameLbl);
        nameLbl.setBounds(540, 80, 50, 18);

        nameField.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        nameField.setSelectedTextColor(new java.awt.Color(193, 187, 234));
        nameField.setSelectionColor(new java.awt.Color(193, 187, 234));
        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });
        addFriendPanel.add(nameField);
        nameField.setBounds(540, 100, 210, 30);

        hostLbl.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        hostLbl.setForeground(new java.awt.Color(204, 105, 119));
        hostLbl.setText("Host");
        addFriendPanel.add(hostLbl);
        hostLbl.setBounds(260, 200, 50, 18);

        hostField.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        hostField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        hostField.setSelectedTextColor(new java.awt.Color(193, 187, 234));
        hostField.setSelectionColor(new java.awt.Color(193, 187, 234));
        hostField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hostFieldActionPerformed(evt);
            }
        });
        addFriendPanel.add(hostField);
        hostField.setBounds(260, 220, 210, 30);

        nicknameLbl.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        nicknameLbl.setForeground(new java.awt.Color(204, 105, 119));
        nicknameLbl.setText("Nickname (Optional)");
        addFriendPanel.add(nicknameLbl);
        nicknameLbl.setBounds(540, 200, 150, 18);

        nicknameField.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        nicknameField.setSelectedTextColor(new java.awt.Color(193, 187, 234));
        nicknameField.setSelectionColor(new java.awt.Color(193, 187, 234));
        nicknameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nicknameFieldActionPerformed(evt);
            }
        });
        addFriendPanel.add(nicknameField);
        nicknameField.setBounds(540, 220, 210, 30);

        addFriendBtn.setBackground(new java.awt.Color(193, 187, 234));
        addFriendBtn.setIcon(new javax.swing.ImageIcon("images/icons/plus.png")); // NOI18N
        addFriendBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addFriendBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFriendBtnActionPerformed(evt);
            }
        });
        addFriendPanel.add(addFriendBtn);
        addFriendBtn.setBounds(700, 270, 50, 40);

        errorAddFriendLbl.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        errorAddFriendLbl.setForeground(new java.awt.Color(255, 102, 0));
        errorAddFriendLbl.setText("Error");
        addFriendPanel.add(errorAddFriendLbl);
        errorAddFriendLbl.setBounds(260, 280, 360, 15);

        leftPanel.setLayout(new java.awt.BorderLayout());

        friendRequestList.setBackground(new java.awt.Color(250, 215, 215));
        friendRequestList.setBorder(null);
        friendRequestList.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        friendRequestList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        leftPanel.add(friendRequestList, java.awt.BorderLayout.CENTER);

        topLeftPanel.setBackground(new java.awt.Color(250, 194, 194));

        friendRequestListLbl.setFont(new java.awt.Font("Nirmala UI", 1, 16)); // NOI18N
        friendRequestListLbl.setForeground(new java.awt.Color(226, 90, 90));
        friendRequestListLbl.setText("Friend Request List");
        topLeftPanel.add(friendRequestListLbl);
        friendRequestListLbl.getAccessibleContext().setAccessibleName("Friend Request");

        acceptFriendBtn.setBackground(new java.awt.Color(255, 102, 102));
        acceptFriendBtn.setIcon(new javax.swing.ImageIcon("images/icons/plus-minus.png")); // NOI18N
        acceptFriendBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptFriendBtnActionPerformed(evt);
            }
        });
        topLeftPanel.add(acceptFriendBtn);

        leftPanel.add(topLeftPanel, java.awt.BorderLayout.NORTH);

        addFriendPanel.add(leftPanel);
        leftPanel.setBounds(0, 0, 210, 550);

        mainFrame.add(addFriendPanel);
        addFriendPanel.setBounds(0, 50, 800, 550);


        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sendMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sendMenuActionPerformed

    private void addFriendMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFriendMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addFriendMenuActionPerformed

    private void homeMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_homeMenuActionPerformed

    private void portFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_portFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_portFieldActionPerformed

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFieldActionPerformed

    private void hostFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hostFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hostFieldActionPerformed

    private void nicknameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nicknameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nicknameFieldActionPerformed

    private void addFriendBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFriendBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addFriendBtnActionPerformed

    private void delFriendBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delFriendBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_delFriendBtnActionPerformed

    private void acceptFriendBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptFriendBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_acceptFriendBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceptFriendBtn;
    private javax.swing.JButton addFriendBtn;
    private javax.swing.JButton addFriendMenu;
    private javax.swing.JPanel addFriendPanel;
    private javax.swing.JPanel contentPage;
    private javax.swing.JButton delFriendBtn;
    private javax.swing.JLabel errorAddFriendLbl;
    private javax.swing.JLabel errorSendingLbl;
    private javax.swing.JList<String> friendList;
    private javax.swing.JLabel friendListLbl;
    private javax.swing.JList<String> friendRequestList;
    private javax.swing.JLabel friendRequestListLbl;
    private javax.swing.JButton homeMenu;
    private javax.swing.JTextField hostField;
    private javax.swing.JLabel hostLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JPanel leftPanel1;
    private javax.swing.JPanel mainFrame;
    private javax.swing.JTextField messageField;
    private javax.swing.JPanel messagePanel;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JTextField nicknameField;
    private javax.swing.JLabel nicknameLbl;
    private javax.swing.JTextField portField;
    private javax.swing.JLabel portLbl;
    private javax.swing.JButton sendMenu;
    private javax.swing.JButton sendMessBtn;
    private javax.swing.JPanel sendingPanel;
    private javax.swing.JButton themeMenu;
    private javax.swing.JPanel topLeftPanel;
    private javax.swing.JPanel topLeftPanel1;
    private javax.swing.JPanel upperBar;
    // End of variables declaration//GEN-END:variables
}
